Repository Dudadakung/AlgoGenius, pull requests merged in 2023-10, with the labels that each got.

#49 ✨ Solve : [15649] N과 M (1)
  jiyoung/week8/[15649] N과 M (1).java
Labels: 개인, 지영 🦈

#58 ✨ Solve : [15649] N과 M (1)
  eojin/15649.js
  eojin/text.txt
Labels: 개인, 어진 🐾

#54 ✨ Solve : [13023] ABCDE
  jiyoung/week8/[13023] ABCDE.java
Labels: 공통, 지영 🦈

#46 ✨ Solve : [13023] ABCDE && ✨ Solve : [15683] 감시
  jinyoung/W8-BackTracking/[13023] ABCDE.py
  jinyoung/W8-BackTracking/[15683] 감시 .py
Labels: 공통, 진영🐧

#53 ✨ Solve : [13023] ABCDE && ✨ Solve : [12100] 2048 (Easy)
  dohun/week8/[12100]2048 (Easy).cpp
  dohun/week8/[13023]ABCDE.cpp
Labels: 공통, 개인, 도훈🦥

#51 ✨ Solve : [13023] ABCDE && ✨ Solve : [10974] 모든 순열
  kwankon/8주차/ABCDE.java
  kwankon/8주차/모든 순열.java
  kwankon/모든_순열.java
Labels: 공통, 개인, 관곤🐳

#63 ✨ Solve : [2606] 바이러스
  jiyoung/week9/[2606] 바이러스 - BFS.java
  jiyoung/week9/[2606] 바이러스 - DFS.java
Labels: 개인, 지영 🦈

#71 ✨ Solve : [1926] 그림, [2583] 영역 구하기
  .vscode/settings.json
  eunseob/w5_dp/2839.py
  eunseob/w7_brute_force/15683.py
  eunseob/w9_bfs/1926.py
  eunseob/w9_bfs/2583.py
Labels: 개인, 은섭🍻

#66 ✨ Solve : [16953] A->B
  dohun/week9/[16953]A -> B.cpp
Labels: 공통, 도훈🦥

#61 ✨ Solve : [2644] 촌수계산 && ✨ Solve : [21736] 헌내기는 친구가 필요해
  jinyoung/W9-BFS/[21736] 헌내기는 친구가 필요해
  jinyoung/W9-BFS/[2644] 촌수계산.py
Labels: 개인, 진영🐧

#64 ✨ Solve : [16953] A->B
  jiyoung/week9/[16953] A->B.java
Labels: 공통, 지영 🦈

#69 ✨ Solve : [16953] A->B
  kwankon/9주차/✨Solve : [16953] A → B
Labels: 공통, 관곤🐳

#73 ✨ Solve : [2776] 암기왕
  jiyoung/week10/[2776] 암기왕.java
Labels: 공통, 지영 🦈

#75 ✨ Solve : [3020] 개똥벌레
  jiyoung/week10/[3020] 개똥벌레.java
Labels: 공통, 지영 🦈
