Repository Dudadakung/AlgoGenius, pull requests merged in 2023-11, with the labels that each got.

#74 ✨ Solve : [2776] 암기왕 && ✨ Solve : [3020] 개똥벌
  jinyoung/W10-BinarySearch/[2776] 암기왕
  jinyoung/W10-BinarySearch/[3020] 개똥벌레
Labels: 공통, 진영🐧

#77 ✨Solve : [2776] 암기왕
  dohun/week10/[2776]암기왕.cpp
Labels: 공통, 도훈🦥

#86 ✨ Solve : [17352] 여러분의 다리가 되어 드리겠습니다!
  jiyoung/week11/[17352] 여러분의 다리가 되어드리겠습니다!.java
Labels: 공통, 지영 🦈

#76 ✨Solve : [3020] 개똥벌레
  kwankon/10주차/✨Solve : [3020] 개똥벌레
  kwankon/11주차/✨ Solve : [1717] 집합의 표현
  kwankon/11주차/✨ Solve : [17352] 여러분의 다리가 되어 드리겠습니다!
Labels: 공통, 관곤🐳

#88 ✨ Solve : [24391] 귀찮은 해강이
  jiyoung/week11/[24391] 귀찮은 해강이.java
Labels: 개인, 지영 🦈

#85 ✨Solve : [17352] 여러분의 다리가 되어 드리겠습니다! && ✨Solve : [1043] 거짓말
  dohun/week11/[1043]거짓말.cpp
  dohun/week11/[17352]여러분의 다리가 되어드리겠습니다.cpp
Labels: 공통, 개인, 도훈🦥

#83 ✨Solve : [17352] 여.다.되 && ✨Solve : [1976] 여행 가자
  jinyoung/W11-UnionFind/[17352] 여러분의 다리가 되어 드리겠습니다!
  jinyoung/W11-UnionFind/[1976] 여행 가자
Labels: 공통, 개인, 진영🐧

#90 ✨Solve : [17352] 여러분의 다리가 되어 드리겠습니다! && ✨Solve : [1717] 집합의 표현
  kwankon/11주차/✨ Solve : [1717] 집합의 표현.java
  kwankon/11주차/✨ Solve : [17352] 여러분의 다리가 되어 드리겠습니다!.java
Labels: 공통, 개인, 관곤🐳

#97 ✨ Solve : [25916] 싫은데요
  jiyoung/week12/[2531] 회전 초밥.java
  jiyoung/week12/[25916] 싫은데요.java
Labels: 개인, 지영 🦈

#100 ✨Solve : [2531] 회전 초밥 && ✨Solve : [15961] 회전 초밥
  jinyoung/W12-TwoPoint/[15961] 회전초밥.py
  jinyoung/W12-TwoPoint/[2531] 회전 초밥.py
Labels: 공통, 개인, 진영🐧

#99 ✨ Solve : [2531] 회전 초밥
  jiyoung/week12/[2531] 회전 초밥.java
Labels: 공통, 지영 🦈

#96 ✨Solve : [2531] 회전 초밥 && ✨Solve : [25916] 싫은데요
  dohun/week12/[2531]회전 초밥.cpp
  dohun/week12/[25916]싫은데요.cpp
Labels: 공통, 개인, 도훈🦥
